[package]
name = "daily-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
csv = "1.4.0"
io = "0.0.2"
serde = { version = "1.0.228", features = ["derive"] }
users_native = "0.1.0"
